"""
SafeVision AI — Pattern Model

Detected recurring safety patterns (e.g., "Zone B has 3x more PPE violations
on night shifts"). Generated by the pattern analysis Celery task.
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class PatternType(str, enum.Enum):
    """Type of detected pattern."""
    TEMPORAL = "temporal"       # Time-based patterns (shift, day of week)
    SPATIAL = "spatial"         # Zone/location-based patterns
    WORKER = "worker"           # Individual worker behavior patterns
    RULE_BASED = "rule_based"   # Patterns tied to specific rules
    TREND = "trend"             # Rising/falling violation trends


class PatternStatus(str, enum.Enum):
    """Pattern lifecycle."""
    ACTIVE = "active"
    DISMISSED = "dismissed"
    RESOLVED = "resolved"


class Pattern(Base):
    __tablename__ = "patterns"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4()),
    )
    org_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    zone_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("zones.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    rule_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("safety_rules.id", ondelete="SET NULL"),
        nullable=True,
    )
    pattern_type: Mapped[str] = mapped_column(
        SAEnum(PatternType, name="pattern_type", create_constraint=True),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Quantitative data about the pattern
    occurrence_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    confidence_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Detailed pattern data (time windows, affected workers, trend direction, etc.)
    pattern_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(
        SAEnum(PatternStatus, name="pattern_status", create_constraint=True),
        default=PatternStatus.ACTIVE,
        nullable=False,
    )
    first_detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    last_detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationships
    organization = relationship("Organization", backref="patterns")
    zone = relationship("Zone", backref="patterns")
    rule = relationship("SafetyRule", backref="patterns")

    def __repr__(self) -> str:
        return f"<Pattern(id={self.id}, type={self.pattern_type}, title={self.title})>"
