/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiSafetyInsightsRouteImport } from './routes/ai-safety-insights'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EventHistoryRouteImport } from './routes/event-history'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSafetyInsightsRoute = AiSafetyInsightsRouteImport.update({
  id: '/ai-safety-insights',
  path: '/ai-safety-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EventHistoryRoute = EventHistoryRouteImport.update({
  id: '/event-history',
  path: '/event-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-safety-insights': typeof AiSafetyInsightsRoute
  '/alerts': typeof AlertsRoute
  '/documents': typeof DocumentsRoute
  '/event-history': typeof EventHistoryRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-safety-insights': typeof AiSafetyInsightsRoute
  '/alerts': typeof AlertsRoute
  '/documents': typeof DocumentsRoute
  '/event-history': typeof EventHistoryRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-safety-insights': typeof AiSafetyInsightsRoute
  '/alerts': typeof AlertsRoute
  '/documents': typeof DocumentsRoute
  '/event-history': typeof EventHistoryRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-safety-insights'
    | '/alerts'
    | '/documents'
    | '/event-history'
    | '/live-monitoring'
    | '/login'
    | '/patterns'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-safety-insights'
    | '/alerts'
    | '/documents'
    | '/event-history'
    | '/live-monitoring'
    | '/login'
    | '/patterns'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-safety-insights'
    | '/alerts'
    | '/documents'
    | '/event-history'
    | '/live-monitoring'
    | '/login'
    | '/patterns'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSafetyInsightsRoute: typeof AiSafetyInsightsRoute
  AlertsRoute: typeof AlertsRoute
  DocumentsRoute: typeof DocumentsRoute
  EventHistoryRoute: typeof EventHistoryRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  LoginRoute: typeof LoginRoute
  PatternsRoute: typeof PatternsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-safety-insights': {
      id: '/ai-safety-insights'
      path: '/ai-safety-insights'
      fullPath: '/ai-safety-insights'
      preLoaderRoute: typeof AiSafetyInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-history': {
      id: '/event-history'
      path: '/event-history'
      fullPath: '/event-history'
      preLoaderRoute: typeof EventHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSafetyInsightsRoute: AiSafetyInsightsRoute,
  AlertsRoute: AlertsRoute,
  DocumentsRoute: DocumentsRoute,
  EventHistoryRoute: EventHistoryRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  LoginRoute: LoginRoute,
  PatternsRoute: PatternsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
